CREATE TABLE tb_reg_dipu (
id_reg INT (10) AUTO_INCREMENT NOT NULL,
nombre VARCHAR (25),
apellido_p VARCHAR (50),
apellido_m VARCHAR (50),
edad INT (2),
edo_civil VARCHAR (50),
municipio VARCHAR (50),
distrito VARCHAR (50),
colonia VARCHAR (50),
calle_numero VARCHAR (50),
zona VARCHAR (50),
seccion VARCHAR (50),
seccion_grado_urbanizacion VARCHAR (50),
email VARCHAR (50),
telefono VARCHAR (25),
movil VARCHAR (25),
nivel_educativo VARCHAR (50),
ocupacion VARCHAR (50),
cargos_publicos VARCHAR (50),
periodo VARCHAR (50),
lugar VARCHAR (50),
influencia VARCHAR (255),
asoc_religiosa VARCHAR (50),
otra VARCHAR (50),
tipo_nivel_educativo VARCHAR (50),
nombre_cto_edu VARCHAR (50),
direccion_cto_educativo VARCHAR (255),
privada_publica VARCHAR (50),
tipo_actividad VARCHAR (50),
nombre_asociacion VARCHAR (50),
direccion_asociacion VARCHAR (255),
consejos VARCHAR (50),
delegados VARCHAR (50),
nombre_lider VARCHAR (50),
filiacion_politica VARCHAR (50),
PRIMARY KEY(id_reg)
)
